server:
  applicationConnectors:
    - type: http
      port: 7070
      bindHost: 0.0.0.0
  adminConnectors:
    - type: http
      port: 7071
      bindHost: 0.0.0.0

swagger:
  resourcePackage: com.station.cooking.cheese.api_rest.resource


  #logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
#  level: INFO